/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm.machine;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author omarTarek
 */
public class changePassword extends javax.swing.JFrame {

    public changePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordconfirmation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(367, 295));
        getContentPane().setLayout(null);

        Password.setBackground(new java.awt.Color(0, 102, 255));
        Password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(80, 120, 270, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("تغيير كلمه السر");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 40, 130, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("كلمة السر الجديدة :");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 120, 120, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("تأكيد كلمه السر :");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 190, 110, 30);

        passwordconfirmation.setBackground(new java.awt.Color(0, 102, 255));
        passwordconfirmation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordconfirmation.setForeground(new java.awt.Color(255, 255, 255));
        passwordconfirmation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordconfirmation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordconfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordconfirmationActionPerformed(evt);
            }
        });
        getContentPane().add(passwordconfirmation);
        passwordconfirmation.setBounds(80, 190, 270, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" عودة ");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 310, 140, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" حفظ ");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 310, 140, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/machine/change.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 540, 370);

        setSize(new java.awt.Dimension(551, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void passwordconfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordconfirmationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordconfirmationActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Login log = new Login();
        if (log.changepass == 1) {
            JOptionPane.showMessageDialog(null, "لا يمكن الخروج قبل تغير كلمه السر", "حدث خطأ", 0, new ImageIcon("R.png"));

        } else if (log.changepass == 0) {
            setVisible(false);
            menu open = new menu();
            open.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String newPassword = Password.getText().trim();
        String conPassword = passwordconfirmation.getText().trim();
        Login log = new Login();
        connection Class = new connection();
        ResultSet rs = null;
        if (!(newPassword.matches("[0-9]*")) && !(conPassword.matches("[0-9]*"))) {
            JOptionPane.showMessageDialog(null, "برجاء بإدخال ارقام فقط", "حدث خطأ", 0, new ImageIcon("R.png"));
        } else if (!newPassword.equals(conPassword)) {
            JOptionPane.showMessageDialog(null, "كلمتان السر غير متطابقتان", "حدث خطأ", 0, new ImageIcon("R.png"));
        } else if (newPassword.equals("") && conPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "قم بإدخال كلمه سر الجديد", "حدث خطأ", 0, new ImageIcon("R.png"));
        } else if (newPassword.length() != 4) {
            JOptionPane.showMessageDialog(null, "يجب ان تتكون كلمه السر من اربع ارقام", "حدث خطأ", 0, new ImageIcon("R.png"));
        }else if(newPassword.equals("0000")){
            JOptionPane.showMessageDialog(null, "لا يمكن استخدام كلمه السر هذه", "حدث خطأ", 0, new ImageIcon("R.png"));
        }else if (newPassword.equals(conPassword)) {
            try {
                rs = Class.selectUser(log.user1, log.password1);
                if (newPassword.equals(rs.getString(2))) {
                    JOptionPane.showMessageDialog(null, "كلمة السر التي ادخلتها متطابقه مع كلمة السر القديمه", "حدث خطأ", 0, new ImageIcon("R.png"));
                } else {
                    Class.updatePass(log.user1, newPassword);
                    JOptionPane.showMessageDialog(null, "تم تغيير كلمه السر بنجاح", "تمت العمليه بنجاح", 0, new ImageIcon("OIP_2.png"));
                    log.password1 = newPassword;
                    if (log.changepass == 1) {
                        log.changepass = 0;
                    }
                    int x = Class.cheekClose();
                    if (x == 1) {
                        setVisible(false);
                        new menu().setVisible(true);
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "حدث خطأ", 0, new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField passwordconfirmation;
    // End of variables declaration//GEN-END:variables
}
