/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm.machine;

import java.sql.ResultSet;
import java.sql.SQLException;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author omarTarek
 */
public class Deposit extends javax.swing.JFrame {

    public static int i;

    public Deposit() {
        connection Class = new connection();
        Login log = new Login();
        ResultSet rs = null;
        try {
            initComponents();
            rs = Class.selectUser(log.user1, log.password1);
            show.setText(rs.getString(3));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "حدث خطأ", 0, new ImageIcon("R.png"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        depos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 295));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("عودة");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 310, 130, 50);

        depos.setBackground(new java.awt.Color(0, 51, 153));
        depos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        depos.setForeground(new java.awt.Color(255, 255, 255));
        depos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        depos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        depos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposActionPerformed(evt);
            }
        });
        getContentPane().add(depos);
        depos.setBounds(60, 190, 270, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("المبلغ :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 190, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("قم بإدخال مبلغ لإيداعه في الحساب");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 90, 290, 28);

        show.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(show);
        show.setBounds(110, 20, 120, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("جنية مصري");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 20, 80, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("إيداع");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 310, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/machine/dep.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 380);

        setSize(new java.awt.Dimension(505, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setVisible(false);
        menu m = new menu();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void deposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposActionPerformed

    }//GEN-LAST:event_deposActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String deposite = depos.getText().trim();
        connection c = new connection();
        Connection conn = null;
        try {
            i = Integer.parseInt(deposite);
            if (!(deposite.matches("[0-9]*"))) {
                JOptionPane.showMessageDialog(null, "برجاء إدخال ارقام فقط", "حدث خطأ", 0, new ImageIcon("R.png"));
            } else if (deposite.equals("")) {
                JOptionPane.showMessageDialog(null, "برجاء يجب إدخال المبلغ", "حدث خطأ", 0, new ImageIcon("R.png"));
            }else if(i>10000){
                    JOptionPane.showMessageDialog(null, "لا يمكن إداع هذا المبلغ الحد الاقصي للإداع هو 10000", "حدث خطأ", 0, new ImageIcon("R.png"));
                } else if (i < 50) {
                JOptionPane.showMessageDialog(null, " جنية50 لا يمكن إداع مبلغ اقل من", "حدث خطأ", 0, new ImageIcon("R.png"));
            } else {
                if (i % 50 == 0) {
                    setVisible(false);
                    Deposit2 d = new Deposit2();
                    d.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "جنية 50لا يمكن الإداع بعمله اقل من ", "حدث خطأ", 0, new ImageIcon("R.png"));
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "برجاء إدخال ارقام فقط", "حدث خطأ", 0, new ImageIcon("R.png"));
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField depos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
