/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm.machine;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author omarTarek
 */
public class Login extends javax.swing.JFrame {

    public static String user1;
    public static String password1;
    public static int changepass=0;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        Login = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(400, 310));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("مرحباً بك في ماكينة الصرف الالي");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 280, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("إسم المستخدم :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 110, 100, 30);

        user.setBackground(new java.awt.Color(0, 51, 153));
        user.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(80, 110, 260, 26);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("كلمه السر :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 190, 70, 30);

        password.setBackground(new java.awt.Color(0, 51, 153));
        password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(80, 190, 260, 30);

        Login.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("دخول");
        Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(370, 280, 120, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("إغلاق ");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 280, 120, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/machine/Untitled4.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(413, 250));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -4, 510, 360);

        setSize(new java.awt.Dimension(523, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        
        connection Class = new connection();
        ResultSet rs = null;
        try {
            String chek_user = user.getText().trim();
            String chek_password = password.getText().trim();
            rs = Class.selectAdmin(chek_user, chek_password);
            user1 = rs.getString(1);
            password1 = rs.getString(2);
            this.setVisible(false);
            new AdminMenu().setVisible(true);
        } catch (SQLException ex) {
            String chek_user = user.getText().trim();
            String chek_password = password.getText().trim();
            try {
                rs = Class.selectUser(chek_user, chek_password);
                user1 = rs.getString(1);
                password1 = rs.getString(2);
                if (chek_password.equals("0000")) {
                    JOptionPane.showMessageDialog(null, "يجب تغير كلمة السر", "حدث خطأ", 0, new ImageIcon("R.png"));
                    changepass=1;
                    this.setVisible(false);
                    new changePassword().setVisible(true);
                }else if(!chek_password.equals("0000")){
                this.setVisible(false);
                new menu().setVisible(true);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, " اسم المستخدم او كلمه السر الذي ادخلتها خطأ", "حدث خطأ", 0, new ImageIcon("R.png"));
            }
        }

    }//GEN-LAST:event_LoginMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            connection Class = new connection();
        ResultSet rs = null;
        try {
            String chek_user = user.getText().trim();
            String chek_password = password.getText().trim();
            rs = Class.selectAdmin(chek_user, chek_password);
            user1 = rs.getString(1);
            password1 = rs.getString(2);
            this.setVisible(false);
            new AdminMenu().setVisible(true);
        } catch (SQLException ex) {
            String chek_user = user.getText().trim();
            String chek_password = password.getText().trim();
            try {
                rs = Class.selectUser(chek_user, chek_password);
                user1 = rs.getString(1);
                password1 = rs.getString(2);
                if (chek_password.equals("0000")) {
                    JOptionPane.showMessageDialog(null, "يجب تغير كلمة السر", "حدث خطأ", 0, new ImageIcon("R.png"));
                    changepass=1;
                    this.setVisible(false);
                    new changePassword().setVisible(true);
                }else if(!chek_password.equals("0000")){
                this.setVisible(false);
                new menu().setVisible(true);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, " اسم المستخدم او كلمه السر الذي ادخلتها خطأ", "حدث خطأ", 0, new ImageIcon("R.png"));
            }
        }
        }
    }//GEN-LAST:event_LoginKeyPressed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             System.exit(0);
        }
    }//GEN-LAST:event_jLabel5KeyPressed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_userKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField password;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
