/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm.machine;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dell 2
 */
public class transformation extends javax.swing.JFrame {

    /**
     * Creates new form transformation
     */
    public transformation() {
        connection Class = new connection();
        Login log = new Login();
        ResultSet rs = null;
        try {
            initComponents();
            rs = Class.selectUser(log.user1, log.password1);
            show.setText(rs.getString(3));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "لم يتم تحويل المبلغ تأكد من ان هذا المستخدم موجود", "حدث خطأ", 0, new ImageIcon("R.png"));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depos1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        User = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        depos1.setBackground(new java.awt.Color(0, 51, 153));
        depos1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        depos1.setForeground(new java.awt.Color(255, 255, 255));
        depos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        depos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        depos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depos1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 350));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("اسم المستخدم :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 110, 100, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" تحويل اموال");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 20, 110, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("المبلغ :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 170, 70, 28);

        Amount.setBackground(new java.awt.Color(0, 204, 204));
        Amount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Amount.setForeground(new java.awt.Color(255, 255, 255));
        Amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Amount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });
        getContentPane().add(Amount);
        Amount.setBounds(60, 170, 230, 28);

        User.setBackground(new java.awt.Color(0, 204, 204));
        User.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        User.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        getContentPane().add(User);
        User.setBounds(60, 110, 230, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("عودة");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 230, 130, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("تحويل");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 230, 130, 50);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("جنية مصري");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 50, 80, 30);

        show.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(show);
        show.setBounds(120, 50, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/machine/transform2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, 0, 460, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depos1ActionPerformed

    }//GEN-LAST:event_depos1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        connection Class = new connection();
        Login log = new Login();
        ResultSet rs1 = null;
        ResultSet rs2 = null;
        String user = User.getText().trim();
        String amount = Amount.getText().trim();
        if (!amount.matches("[0-9]*")) {
            JOptionPane.showMessageDialog(null, "برجاء إدخال ارقام صحيحه فقط", "حدث خطأ", 0, new ImageIcon("R.png"));
        } else {
            try {
                rs1 = Class.selectUser(log.user1, log.password1);
                rs2 = Class.SearchtUser(user);
                double user1 = rs1.getDouble(3);
                double user2 = rs2.getDouble(3);
                double trans = Double.parseDouble(amount);
                if (trans <= 0) {
                    JOptionPane.showMessageDialog(null, "لا يمكن تحويل هذا المبلغ", "حدث خطأ", 0, new ImageIcon("R.png"));
                } else if (trans >30000) {
                     JOptionPane.showMessageDialog(null, "لا يمكن تحويل هذا المبلغ الحد الاقصي للتحويل هو 30000", "حدث خطأ", 0, new ImageIcon("R.png"));
                } else if (trans > user1) {
                    JOptionPane.showMessageDialog(null, "هذا المبلغ غير متوفر", "حدث خطأ", 0, new ImageIcon("R.png"));
                } else {
                    double sub = user1 - trans;
                    double sum = user2 + trans;
                    Class.updateTable(sub, log.user1);
                    Class.updateTable(sum, user);
                    Class.insertTable(log.user1, "transform-" + user, trans);
                    JOptionPane.showMessageDialog(null, "تم التحويل بنجاح", "تمت العمليه بنجاح", 0, new ImageIcon("OIP_2.png"));
                    int x = Class.cheekClose();
                    if (x == 1) {
                        new menu().setVisible(true);
                        setVisible(false);
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "حدث خطأ", 0, new ImageIcon("R.png"));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "برجاء إدخال ارقام فقط", "حدث خطأ", 0, new ImageIcon("R.png"));
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed

    }//GEN-LAST:event_UserActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed

    }//GEN-LAST:event_AmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Amount;
    public static javax.swing.JTextField User;
    public static javax.swing.JTextField depos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
